// lib/historyCategories.ts
// Single source of truth for all 17 history subcategories.
// Imported by: AdminPanel.tsx, SchedulerPanel.tsx, route-generate-history.ts, route-generate-articles.ts
// NOTE: topicPool removed — topics are now managed via the topic_pool DB table.

export const HISTORY_CATEGORIES: Record<string, {
  label: string;
  emoji: string;
  era: string;
  imageQueries: string[];
}> = {
  'ancient-civilizations': {
    label: 'Ancient Civilizations',
    emoji: '🏛️',
    era:   'ancient',
    imageQueries: [
      'ancient ruins archaeology excavation',
      'Egyptian pyramids Giza desert',
      'ancient Greece Parthenon Athens',
      'Mesopotamia ancient ruins Iraq',
      'ancient Rome Colosseum ruins',
      'Indus Valley Mohenjo-daro ruins',
      'ancient civilization stone carving',
      'archaeological dig ancient artifacts',
    ],
  },
  'medieval-feudal': {
    label: 'Medieval & Feudal',
    emoji: '⚔️',
    era:   'medieval',
    imageQueries: [
      'medieval castle ruins stone fortress',
      'knights armor medieval sword',
      'medieval cathedral gothic architecture',
      'crusades middle ages historical',
      'medieval town village reconstruction',
      'Byzantine mosaic Constantinople',
      'Mongol warrior historical artwork',
      'medieval manuscript illuminated',
    ],
  },
  'age-of-exploration': {
    label: 'Age of Exploration',
    emoji: '🧭',
    era:   'early-modern',
    imageQueries: [
      'old sailing ship ocean historical',
      'antique map parchment exploration',
      'compass navigation maritime historical',
      'Portuguese caravel historic ship',
      'ancient trade route spice market',
      'explorer navigation stars ocean',
      'colonial era harbor port ships',
      'old world map cartography atlas',
    ],
  },
  'revolutions-politics': {
    label: 'Revolutions & Politics',
    emoji: '✊',
    era:   'modern',
    imageQueries: [
      'revolution protest historical crowd',
      'French Revolution historical painting',
      'Bastille storming historical artwork',
      'political uprising streets historical',
      'independence movement historical photo',
      'revolution barricades streets historical',
      'political leaders historical meeting',
      'declaration independence historical document',
    ],
  },
  'world-wars-conflicts': {
    label: 'World Wars & Conflicts',
    emoji: '🎖️',
    era:   'modern',
    imageQueries: [
      'World War memorial cemetery soldiers',
      'World War trench warfare historical',
      'WWII military soldiers historical photo',
      'war memorial monument remembrance',
      'battlefield ruins war historical',
      'military aircraft WWII historical',
      'cold war Berlin wall historical',
      'war veterans soldiers historical portrait',
    ],
  },
  'colonial-imperial': {
    label: 'Colonial & Imperial',
    emoji: '🌐',
    era:   'modern',
    imageQueries: [
      'colonial era architecture building',
      'empire historical map world',
      'colonial port harbor historical ships',
      'independence movement crowd historical',
      'imperial palace historical architecture',
      'colonial era document treaty historical',
      'African independence historical photo',
      'empire ruins archaeological site',
    ],
  },
  'human-rights-movements': {
    label: 'Human Rights Movements',
    emoji: '🕊️',
    era:   'modern',
    imageQueries: [
      'civil rights march protest historical',
      'suffragette women protest historical',
      'human rights demonstration historical',
      'Gandhi Salt March historical photo',
      'civil rights movement historical crowd',
      'abolition slavery historical monument',
      'labor movement workers historical strike',
      'peace protest march historical street',
    ],
  },
  'science-technology': {
    label: 'Science & Technology',
    emoji: '🔬',
    era:   'all',
    imageQueries: [
      'science laboratory historical vintage',
      'telescope observatory astronomy historical',
      'industrial revolution machinery historical',
      'ancient scientific instrument astrolabe',
      'early aviation Wright brothers historical',
      'scientific discovery laboratory equipment',
      'space exploration rocket launch NASA',
      'ancient clockwork mechanism gears',
    ],
  },
  'religion-philosophy': {
    label: 'Religion & Philosophy',
    emoji: '📿',
    era:   'all',
    imageQueries: [
      'ancient temple religious architecture',
      'philosopher ancient manuscript scroll',
      'cathedral interior gothic architecture',
      'religious ceremony ancient historical',
      'monastery ancient stone building',
      'sacred text ancient manuscript',
      'temple ruins archaeological site',
      'philosophy ancient Greek sculpture',
    ],
  },
  'cultural-social': {
    label: 'Cultural & Social',
    emoji: '🎭',
    era:   'all',
    imageQueries: [
      'cultural festival historical celebration',
      'ancient art museum artifact',
      'historical textile fashion costume',
      'ancient theater amphitheater ruins',
      'traditional music instrument historical',
      'cultural heritage craft artisan',
      'ancient market bazaar historical',
      'historical painting renaissance art museum',
    ],
  },
  'economic-trade': {
    label: 'Economic & Trade',
    emoji: '🏺',
    era:   'all',
    imageQueries: [
      'Silk Road ancient trade caravan',
      'ancient market trade spices bazaar',
      'historical coins currency ancient',
      'merchant ship trade historical port',
      'ancient ledger accounting book historical',
      'trade route map historical parchment',
      'economic center historical city ruins',
      'ancient gold treasure historical artifact',
    ],
  },
  'military-warfare': {
    label: 'Military & Warfare',
    emoji: '🗡️',
    era:   'all',
    imageQueries: [
      'ancient battlefield historical warfare',
      'military armor weapons historical museum',
      'siege castle medieval warfare',
      'ancient warrior sword shield historical',
      'military strategy map historical war room',
      'battlefield monument memorial historical',
      'ancient fortification wall ruins',
      'historical military commander portrait',
    ],
  },
  'regional-history': {
    label: 'Regional History',
    emoji: '🗺️',
    era:   'all',
    imageQueries: [
      'ancient Africa kingdom ruins historical',
      'Angkor Wat Cambodia temple ruins',
      'Mughal architecture India historical',
      'ancient Americas ruins civilization',
      'African historical architecture monument',
      'regional heritage temple ancient',
      'ancient city ruins excavation',
      'cultural heritage world site landmark',
    ],
  },
  'archaeology-mysteries': {
    label: 'Archaeology & Mysteries',
    emoji: '🔍',
    era:   'all',
    imageQueries: [
      'archaeological excavation dig site ruins',
      'ancient mystery ruins stone circle',
      'archaeological artifact museum display',
      'ancient ruins archaeological site',
      'Stonehenge mystery stone ancient',
      'Pompeii ruins archaeological site',
      'ancient cave painting archaeology',
      'lost city ruins jungle discovery',
    ],
  },
  'famous-figures': {
    label: 'Famous Figures & Leaders',
    emoji: '👑',
    era:   'all',
    imageQueries: [
      'historical portrait leader ancient',
      'historical figure sculpture monument',
      'famous leader historical portrait museum',
      'ancient ruler emperor historical artwork',
      'historical biography portrait painting',
      'leader monument memorial historical',
      'ancient king queen historical sculpture',
      'famous historical figure bust museum',
    ],
  },
  // ── NEW CATEGORIES ──────────────────────────────────────────────────────────
  'beyond-human-limits': {
    label: 'Beyond Human Limits',
    emoji: '🚀',
    era:   'all',
    imageQueries: [
      'human achievement breakthrough historical',
      'impossible engineering feat construction',
      'moon landing space achievement NASA',
      'first flight aviation Wright brothers',
      'engineering marvel historical monument',
      'scientific breakthrough discovery moment',
      'human endurance survival extreme historical',
      'record breaking achievement triumph historical',
    ],
  },
  'historys-unsung-heroes': {
    label: "History's Unsung Heroes",
    emoji: '⭐',
    era:   'all',
    imageQueries: [
      'unsung hero historical portrait courage',
      'ordinary people extraordinary acts historical',
      'forgotten hero memorial monument historical',
      'resilience courage ordinary person historical',
      'humanitarian selfless act historical photo',
      'hidden history hero recognition portrait',
      'courage adversity overcome historical story',
      'community strength hope historical people',
    ],
  },
};