// lib/historyCategories.ts
// Single source of truth for all 15 history subcategories.
// Imported by: AdminPanel.tsx, route-generate-history.ts, route-generate-articles.ts

export const HISTORY_CATEGORIES: Record<string, {
    label: string;
    emoji: string;
    era: string;
    topicPool: string[];
    imageQueries: string[];
  }> = {
    'ancient-civilizations': {
      label: 'Ancient Civilizations', emoji: '🏛️', era: 'ancient',
      topicPool: [
        'the engineering genius behind the Egyptian pyramids that modern architects still cannot replicate',
        'the real reason Rome fell — not barbarians, but something far more internal and surprising',
        'the Mesopotamian city of Uruk — the world\'s first true metropolis 5000 years before New York',
        'the hidden female pharaohs of Egypt that male successors tried to erase from history',
        'the Indus Valley Civilization\'s sewage system that outclassed Rome by 2000 years',
        'the Persian Empire\'s surprisingly tolerant policies that history books credit to others',
        'the real story of Cleopatra — polyglot strategist, not just a romantic figure',
        'the Minoan civilization of Crete whose sudden collapse baffles archaeologists to this day',
        'ancient China\'s Han Dynasty bureaucracy — the world\'s first civil service exam system',
        'the Greek invention of democracy that was far more brutal than textbooks admit',
      ],
      imageQueries: ['ancient ruins archaeology excavation', 'Egyptian pyramids Giza desert', 'ancient Rome Colosseum ruins', 'Indus Valley Mohenjo-daro ruins'],
    },
    'medieval-feudal': {
      label: 'Medieval & Feudal', emoji: '⚔️', era: 'medieval',
      topicPool: [
        'the Black Death\'s hidden silver lining — how the plague accidentally ended feudalism',
        'medieval knights: the brutal reality behind the romantic legend of chivalry',
        'the real Crusades — what actually happened when East met West in the Holy Land',
        'the Mongol Empire\'s postal system faster than anything Europe had for 500 more years',
        'the female rulers of medieval Europe who held power while history forgot their names',
        'the Islamic Golden Age — Baghdad as the world\'s center of science when Europe was in darkness',
        'the hidden history of the medieval peasant revolts that almost toppled European kings',
        'the real Vlad the Impaler — brutal tyrant or misunderstood national hero?',
        'the Silk Road\'s medieval golden era — more than just trade, the internet of its day',
        'the Byzantine Empire\'s 1000-year survival strategy historians rarely teach',
      ],
      imageQueries: ['medieval castle ruins stone fortress', 'knights armor medieval sword', 'medieval cathedral gothic architecture', 'Byzantine mosaic Constantinople'],
    },
    'age-of-exploration': {
      label: 'Age of Exploration', emoji: '🧭', era: 'early-modern',
      topicPool: [
        'the Chinese explorer Zheng He who reached Africa 70 years before Columbus reached America',
        'what Columbus actually found — and what he thought he found — in 1492',
        'the Polynesian navigators who crossed the Pacific using stars 1000 years before Europeans',
        'the brutal reality of the Portuguese spice trade routes',
        'Ibn Battuta — the medieval Moroccan traveler who covered more ground than Marco Polo',
        'the maps that preceded European exploration and the cartographers the West prefers to forget',
        'the real story of Magellan\'s circumnavigation — including who actually finished it',
        'the Aztec and Inca empires\' extensive trade networks before European contact',
        'how the Dutch East India Company became the world\'s first multinational corporation',
        'the hidden role of African navigators in shaping exploration routes',
      ],
      imageQueries: ['old sailing ship ocean historical', 'antique map parchment exploration', 'compass navigation maritime historical', 'ancient trade route spice market'],
    },
    'revolutions-politics': {
      label: 'Revolutions & Politics', emoji: '✊', era: 'modern',
      topicPool: [
        'what the French Revolution actually achieved — and what it destroyed — beyond the guillotine stories',
        'the American Revolution\'s dirty secret: Founding Fathers owned slaves while writing about freedom',
        'the Russian Revolution\'s first weeks — genuine liberation before it turned',
        'the Haitian Revolution — the only successful slave revolt history books almost never teach',
        'how the 1848 revolutions across Europe all failed — and why that shaped the modern world',
        'the Mexican Revolution\'s Zapata and Villa — what they stood for versus the myth',
        'the Iranian Constitutional Revolution of 1906 — the forgotten democratic movement',
        'how the Chinese Revolution of 1911 ended 2000 years of imperial rule overnight',
        'the Velvet Revolutions of 1989 — Soviet bloc collapsed in 6 months without major battle',
        'the real reasons behind the Arab Spring — why Western media fundamentally misread it',
      ],
      imageQueries: ['revolution protest historical crowd', 'French Revolution historical painting', 'political uprising streets historical', 'independence movement historical'],
    },
    'world-wars-conflicts': {
      label: 'World Wars & Conflicts', emoji: '🎖️', era: 'modern',
      topicPool: [
        'the real trigger of WWI — not the assassination but the 40-year alliance system',
        'the Christmas Truce of 1914 — when soldiers on both sides stopped fighting for a day',
        'the Holocaust\'s lesser-known victims — Roma, disabled, Soviet POWs alongside Jewish communities',
        'the Cold War proxy conflicts that killed millions while superpowers avoided direct confrontation',
        'the Korean War — still technically ongoing — the conflict the world agreed to forget',
        'the role of African and Asian soldiers in WWI and WWII that European history minimizes',
        'the Nanking Massacre — China\'s most traumatic WWII memory and Japan\'s continuing silence',
        'the Berlin Airlift — the Cold War standoff resolved without firing a single shot',
        'how WWII\'s ending in 1945 planted the seeds of 50 years of Cold War',
        'the Pacific War\'s island hopping strategy and the ordinary soldiers who bore the cost',
      ],
      imageQueries: ['World War memorial cemetery soldiers', 'WWII military soldiers historical photo', 'war memorial monument remembrance', 'cold war Berlin wall historical'],
    },
    'colonial-imperial': {
      label: 'Colonial & Imperial', emoji: '🌐', era: 'modern',
      topicPool: [
        'the British Empire at its peak — 24% of the world\'s land surface controlled by an island nation',
        'the Belgian Congo genocide — King Leopold II\'s rubber terror that killed 10 million Africans',
        'India under the East India Company before it became the British Raj',
        'the Berlin Conference of 1884 — European powers divided Africa without one African present',
        'the real cost of the transatlantic slave trade — numbers, routes, and who participated',
        'the Ottoman Empire\'s millet system — pluralism 400 years before modern multiculturalism',
        'the American colonial era in the Philippines — the forgotten 50-year occupation',
        'how colonialism deliberately destroyed economies to create dependency',
        'the independence movements of the 1940s-60s — why 40 nations got independence in 20 years',
        'the Mughal Empire\'s religious diversity compared to contemporary European intolerance',
      ],
      imageQueries: ['colonial era architecture building', 'empire historical map world', 'colonial port harbor historical ships', 'independence movement crowd historical'],
    },
    'human-rights-movements': {
      label: 'Human Rights Movements', emoji: '🕊️', era: 'modern',
      topicPool: [
        'the Abolitionist movement\'s hidden heroes — freed slaves who drove the campaign',
        'the Suffragette movement\'s violent tactics that history sanitizes into peaceful marches',
        'Gandhi\'s Salt March — why a walk to the sea changed the political calculus of the British Empire',
        'the Montgomery Bus Boycott\'s 381 days — the economic strategy behind the moral cause',
        'the hidden history of disability rights — the longest civil rights struggle with least coverage',
        'the labor movement\'s forgotten martyrs — the Triangle Shirtwaist fire and the rights it created',
        'apartheid\'s financial lifeline — Western corporations that kept it running while condemning it',
        'the UN Declaration of Human Rights 1948 — what was left out and who fought to leave it out',
        'child labor: from common practice to criminal act — how the shift happened',
        'LGBTQ+ history before the 20th century — surprising tolerance and persecution across cultures',
      ],
      imageQueries: ['civil rights march protest historical', 'suffragette women protest historical', 'human rights demonstration historical', 'Gandhi Salt March historical'],
    },
    'science-technology': {
      label: 'Science & Technology', emoji: '🔬', era: 'all',
      topicPool: [
        'the Baghdad Battery — a 2000-year-old object that may have been an actual electric cell',
        'Nikola Tesla\'s suppressed inventions and the corporate war that erased him from textbooks',
        'the forgotten women of computing — Ada Lovelace, Grace Hopper, and the Hidden Figures of NASA',
        'the Antikythera mechanism — a 2000-year-old analog computer that predates modern calculation by 1500 years',
        'the Arab scholars who preserved Greek science and added algebra, algorithms, and astronomy',
        'the industrial revolution\'s child labor — the human cost behind Britain\'s economic miracle',
        'the Manhattan Project\'s scientists who built the bomb and then tried to stop its spread',
        'Galileo vs the Church — the real story is more complex than science vs religion',
        'the Green Revolution\'s double edge — saved billions while creating new dependency problems',
        'Darwin\'s hidden years — 20 years between his voyage and publication of On the Origin of Species',
      ],
      imageQueries: ['science laboratory historical vintage', 'telescope observatory astronomy historical', 'industrial revolution machinery historical', 'ancient scientific instrument astrolabe'],
    },
    'religion-philosophy': {
      label: 'Religion & Philosophy', emoji: '📿', era: 'all',
      topicPool: [
        'the Council of Nicaea 325 AD — how a political meeting decided what Christianity would officially believe',
        'Zoroastrianism\'s enormous influence on Judaism, Christianity, and Islam that few acknowledge',
        'the Buddhist monasteries of ancient India that functioned as universities 1500 years before Oxford',
        'Socrates\'s trial and execution — the real political reasons behind the philosophical charges',
        'the Sufi tradition\'s influence on music, poetry, and tolerance across the Islamic world',
        'why the Spanish Inquisition was both worse and better than popular culture portrays',
        'Confucianism as state ideology — how one philosopher\'s ethics ran China for 2000 years',
        'the Aztec religion\'s complex cosmology that had more in common with physics than superstition',
        'the Protestant Reformation\'s unintended consequences — capitalism, individualism, the nation-state',
        'the historical Jesus vs the theological Christ — what historians actually know',
      ],
      imageQueries: ['ancient temple religious architecture', 'philosopher ancient manuscript scroll', 'cathedral interior gothic architecture', 'religious ceremony ancient historical'],
    },
    'cultural-social': {
      label: 'Cultural & Social', emoji: '🎭', era: 'all',
      topicPool: [
        'the history of fashion as political statement — from sumptuary laws to the suit jacket\'s military origins',
        'how the printing press spread not just literacy but propaganda, heresy, and revolution',
        'the history of coffee houses — the original social media platform that powered the Enlightenment',
        'medieval food culture: what people actually ate (it wasn\'t all brown and grim)',
        'the history of public baths from Rome to the Ottoman hammam to Japanese onsen',
        'how the Renaissance was financed — the Medici bank and the economic engine behind the art',
        'the history of music notation — from oral tradition to written symphonies',
        'the real story of the samurai — their actual role in Japanese society vs Hollywood',
        'ancient Olympic Games vs modern — same, different, and dramatically surprising',
        'the history of language death — how thousands of languages disappeared',
      ],
      imageQueries: ['cultural festival historical celebration', 'ancient art museum artifact', 'historical textile fashion costume', 'ancient theater amphitheater ruins'],
    },
    'economic-trade': {
      label: 'Economic & Trade', emoji: '🏺', era: 'all',
      topicPool: [
        'the Silk Road\'s true scale — not just silk but ideas, diseases, religions, and technologies',
        'how the Dutch Tulip Mania of 1637 became the world\'s first documented speculative bubble',
        'the history of banking — from Mesopotamian grain loans to the Medici\'s double-entry bookkeeping',
        'the Black Death\'s economic aftermath — how the plague actually raised wages for surviving workers',
        'the East India Company: the corporation that ruled a subcontinent with its own army',
        'ancient Rome\'s remarkably modern economy — trade networks, inflation, and monetary crises',
        'how the trans-Saharan gold trade made Mali the wealthiest kingdom in the medieval world',
        'the history of debt — from ancient Sumer\'s clay tablets to modern sovereign debt crises',
        'the Hanseatic League — the medieval merchant alliance that dominated Northern European trade',
        'how the opium trade funded the British Empire and deliberately addicted millions of Chinese',
      ],
      imageQueries: ['Silk Road ancient trade caravan', 'ancient market trade spices bazaar', 'historical coins currency ancient', 'merchant ship trade historical port'],
    },
    'military-warfare': {
      label: 'Military & Warfare', emoji: '🗡️', era: 'all',
      topicPool: [
        'the Battle of Thermopylae: 300 Spartans vs Persia — what actually happened vs the myth',
        'Sun Tzu\'s Art of War: strategies that still work 2500 years later, and the ones that don\'t',
        'the Mongol siege warfare techniques that made them almost unbeatable across three continents',
        'Napoleon\'s military genius vs Napoleon\'s catastrophic overconfidence — the same man, two stories',
        'the Zulu Army\'s tactics that defeated a professional British force at Isandlwana',
        'medieval siege warfare — engineering, psychology, and 3-year standoffs that shaped kingdoms',
        'espionage in WWII — the double agents, codebreakers, and deceptions that actually won the war',
        'the Peloponnesian War — Athens vs Sparta: the world\'s first great power conflict',
        'guerrilla warfare from ancient Parthia to Vietnam — why superpowers keep losing to insurgents',
        'the arms race in ancient times — from bronze swords to iron to the crossbow to the trebuchet',
      ],
      imageQueries: ['ancient battlefield historical warfare', 'military armor weapons historical museum', 'siege castle medieval warfare', 'ancient warrior sword shield historical'],
    },
    'regional-history': {
      label: 'Regional History', emoji: '🗺️', era: 'all',
      topicPool: [
        'the Kingdom of Aksum — the African empire that converted to Christianity before Rome',
        'pre-colonial Latin America\'s sophisticated agricultural terracing systems',
        'the history of Southeast Asia\'s Khmer Empire — Angkor Wat\'s builders and their fate',
        'medieval West Africa\'s Mali and Songhai empires — universities, legal systems, gold reserves',
        'Japan\'s Edo period isolation policy — 250 years of sakoku and modern Japanese identity',
        'the Byzantine Empire\'s eastern survival after Rome\'s fall — 1000 more years of Roman civilization',
        'the Mughal Empire at its peak under Akbar — religious tolerance, arts, and architecture',
        'Australia\'s 60,000-year Aboriginal history — the world\'s oldest continuous civilization',
        'the Aztec capital Tenochtitlan — larger than London when Cortés arrived',
        'Central Asia\'s forgotten role as the world\'s crossroads — steppe empires rise and fall',
      ],
      imageQueries: ['ancient Africa kingdom ruins historical', 'Angkor Wat Cambodia temple ruins', 'Mughal architecture India historical', 'ancient Americas ruins civilization'],
    },
    'archaeology-mysteries': {
      label: 'Archaeology & Mysteries', emoji: '🔍', era: 'all',
      topicPool: [
        'Göbekli Tepe — the 12,000-year-old temple complex that rewrites the history of civilization',
        'the Nazca Lines of Peru — what we know, what we don\'t, and why aliens are not the answer',
        'the mystery of the Bronze Age Collapse — how a dozen civilizations fell simultaneously around 1200 BC',
        'Pompeii\'s preserved city — what daily Roman life actually looked like frozen in ash',
        'the Voynich Manuscript — an undeciphered 15th century book that has beaten every cryptanalyst',
        'Easter Island\'s moai — the real story behind the statues and the population collapse',
        'the Lost City of Z — Colonel Fawcett\'s obsession and what archaeologists found in the Amazon',
        'Çatalhöyük — the 9000-year-old egalitarian city with no streets and no rulers',
        'the Antikythera shipwreck — the archaeological dive revealing a 2000-year-old analog computer',
        'Stonehenge\'s real purpose — what 50 years of new archaeology has actually told us',
      ],
      imageQueries: ['archaeological excavation dig site ruins', 'ancient mystery ruins stone circle', 'Stonehenge mystery stone ancient', 'Pompeii ruins archaeological site'],
    },
    'famous-figures': {
      label: 'Famous Figures & Leaders', emoji: '👑', era: 'all',
      topicPool: [
        'Alexander the Great\'s 10-year campaign — the logistics, the battles, and the man behind the myth',
        'Queen Elizabeth I\'s political genius — how a woman survived in a world built to exclude her',
        'Genghis Khan: mass murderer or the man who created the first free-trade zone across Asia?',
        'Marie Curie\'s double Nobel Prize — and the scientific establishment\'s attempt to sideline her',
        'Abraham Lincoln\'s complex evolving views on race that neither side of modern politics quotes accurately',
        'Suleiman the Magnificent — the Ottoman Sultan who nearly conquered Vienna and built a legal code',
        'Harriet Tubman: not just the Underground Railroad — her role as a Union spy in the Civil War',
        'Mao Zedong\'s economic catastrophes — the Great Leap Forward\'s death toll China won\'t acknowledge',
        'Julius Caesar: the politician who used military glory to seize power, then paid for it',
        'Nikola Tesla vs Thomas Edison — the current war and what it tells us about how innovation works',
      ],
      imageQueries: ['historical portrait leader ancient', 'historical figure sculpture monument', 'famous leader historical portrait museum', 'ancient ruler emperor historical artwork'],
    },
  };