// rss.ts previously fetched RSS feeds for news categories.
// RSS feeds are no longer needed — history content is 100% generated by Groq.
// This file now exports Wikimedia Commons image fetching utilities
// used by the history image pipeline.

const IMAGE_MIN_WIDTH = 800;

export interface WikimediaPhoto {
  id: string;
  url: string;
  alt: string;
  width: number;
  height: number;
  attribution: string;
  license: string;
  licenseUrl: string;
}

function isFreeWikimediaLicense(license: string): boolean {
  if (!license) return false;
  const free = ['cc0', 'cc-by', 'cc by', 'public domain', 'pd', 'cc-sa', 'cc by-sa', 'attribution'];
  return free.some(f => license.toLowerCase().includes(f));
}

function stripHtml(html: string): string {
  return (html ?? '').replace(/<[^>]*>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').trim();
}

// ─── fetchWikimediaImages ─────────────────────────────────────────────────────
// Searches Wikimedia Commons for free-license images related to a history topic.
// Returns up to `count` photos with full attribution metadata.
export async function fetchWikimediaImages(
  searchTerm: string,
  count = 3
): Promise<WikimediaPhoto[]> {
  const photos: WikimediaPhoto[] = [];
  const WIKI_API = 'https://en.wikipedia.org/w/api.php';

  try {
    // Step 1: Search File namespace
    const ctrl1 = new AbortController();
    setTimeout(() => ctrl1.abort(), 8000);
    const sr = await fetch(
      `${WIKI_API}?action=query&list=search&srsearch=${encodeURIComponent(searchTerm)}&srnamespace=6&srlimit=${count * 4}&format=json&origin=*`,
      { signal: ctrl1.signal }
    );
    if (!sr.ok) return photos;
    const sd = await sr.json();
    const results: any[] = sd?.query?.search ?? [];

    for (const result of results) {
      if (photos.length >= count) break;
      if (!result.title?.startsWith('File:')) continue;

      const ctrl2 = new AbortController();
      setTimeout(() => ctrl2.abort(), 6000);
      const ir = await fetch(
        `${WIKI_API}?action=query&titles=${encodeURIComponent(result.title)}&prop=imageinfo&iiprop=url|size|mime|extmetadata&iiurlwidth=1200&format=json&origin=*`,
        { signal: ctrl2.signal }
      );
      if (!ir.ok) continue;
      const id = await ir.json();

      for (const page of Object.values(id?.query?.pages ?? {}) as any[]) {
        const info = page.imageinfo?.[0];
        if (!info) continue;
        if (!['image/jpeg', 'image/png', 'image/webp'].includes(info.mime)) continue;
        if ((info.thumbwidth || info.width) < IMAGE_MIN_WIDTH) continue;
        const license = info.extmetadata?.LicenseShortName?.value ?? '';
        if (!isFreeWikimediaLicense(license)) continue;

        photos.push({
          id:          `wiki_${page.pageid}`,
          url:         info.thumburl || info.url,
          alt:         stripHtml(info.extmetadata?.ImageDescription?.value ?? '') || `${searchTerm} — Wikimedia Commons`,
          width:       info.thumbwidth  || info.width,
          height:      info.thumbheight || info.height,
          attribution: stripHtml(info.extmetadata?.Artist?.value ?? '') || 'Wikimedia Commons contributor',
          license,
          licenseUrl:  info.extmetadata?.LicenseUrl?.value ?? '',
        });
        if (photos.length >= count) break;
      }

      // Small delay to be polite to the API
      await new Promise(r => setTimeout(r, 150));
    }
  } catch (e: any) {
    console.error('fetchWikimediaImages error:', e.message);
  }

  return photos;
}

// ─── fetchWikimediaForArticle ─────────────────────────────────────────────────
// Higher-level helper: tries multiple search terms until it finds enough images.
export async function fetchWikimediaForArticle(
  title: string,
  subcategory: string,
  fallbackQueries: string[],
  count = 3
): Promise<WikimediaPhoto[]> {
  const queries = [
    title.split(' ').slice(0, 6).join(' '),
    ...fallbackQueries,
    subcategory.replace(/-/g, ' '),
    'ancient history ruins',
  ];

  const seen = new Set<string>();
  const results: WikimediaPhoto[] = [];

  for (const query of queries) {
    if (results.length >= count) break;
    const photos = await fetchWikimediaImages(query, count - results.length);
    for (const p of photos) {
      if (!seen.has(p.id)) {
        seen.add(p.id);
        results.push(p);
      }
    }
  }

  return results;
}