-- ARTICLES TABLE
CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT NOT NULL UNIQUE,
    source_name     TEXT NOT NULL,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false
);

CREATE INDEX idx_articles_category ON public.articles(category);
CREATE INDEX idx_articles_score ON public.articles(score);
CREATE INDEX idx_articles_published_date ON public.articles(published_date);
CREATE INDEX idx_articles_is_published ON public.articles(is_published);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- UPDATE TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_settings_updated_at
BEFORE UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- Supabase Migration: Add article images support (updated - skips duplicates)

-- Create article_images table to store multiple images per article
CREATE TABLE IF NOT EXISTS public.article_images (
  id BIGSERIAL PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  alt_text TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  width INTEGER DEFAULT 1200,
  height INTEGER,
  size_kb INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for article_images
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS on article_images
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for article_images
-- Drop existing policies if they exist (optional - comment out if not needed)
-- DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
-- DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Add new columns to articles table (IF NOT EXISTS)
ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS is_draft BOOLEAN DEFAULT TRUE;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS admin_notes TEXT;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS scheduled_publish_date TIMESTAMP WITH TIME ZONE;

-- Create index for is_draft (IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);

-- Add comment
COMMENT ON TABLE article_images IS 'Stores multiple images for each article - supports 4-5 images per article at 1200px minimum width';

-- Verify migration
SELECT 
  'article_images table' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images') as exists
UNION ALL
SELECT 
  'is_draft column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');


-- COMPLETE DATABASE MIGRATION FOR ORIGINAL CONTENT SYSTEM
-- Run this in Supabase SQL Editor
-- FIXED: Removed IF NOT EXISTS from CREATE POLICY (not supported)

-- ============================================================================
-- ARTICLES TABLE - Updated for original content + image support
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT,
    source_name     TEXT,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false,
    is_draft        BOOLEAN DEFAULT true,
    admin_notes     TEXT,
    scheduled_publish_date TIMESTAMPTZ
);

-- Create indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_articles_category ON public.articles(category);
CREATE INDEX IF NOT EXISTS idx_articles_score ON public.articles(score);
CREATE INDEX IF NOT EXISTS idx_articles_published_date ON public.articles(published_date);
CREATE INDEX IF NOT EXISTS idx_articles_is_published ON public.articles(is_published);
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON public.articles(created_at);

-- Enable Row Level Security
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Published articles are publicly readable" ON public.articles;
DROP POLICY IF EXISTS "Admins can read all articles" ON public.articles;

-- RLS Policy: Anyone can read published articles
CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- RLS Policy: Authenticated users (admin) can read all articles
CREATE POLICY "Admins can read all articles"
ON public.articles FOR SELECT
USING (auth.role() = 'authenticated');

-- Update trigger for updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Drop trigger if exists, then create
DROP TRIGGER IF EXISTS update_articles_updated_at ON public.articles;
CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- ARTICLE_IMAGES TABLE - For storing multiple images per article
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.article_images (
  id              BIGSERIAL PRIMARY KEY,
  article_id      BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url       TEXT NOT NULL,
  alt_text        TEXT,
  position        INTEGER NOT NULL DEFAULT 0,
  width           INTEGER DEFAULT 1200,
  height          INTEGER,
  size_kb         INTEGER,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

-- RLS Policies
CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Update trigger for article_images
DROP TRIGGER IF EXISTS update_article_images_updated_at ON public.article_images;
CREATE TRIGGER update_article_images_updated_at
BEFORE UPDATE ON public.article_images
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- SETTINGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Settings are publicly readable" ON public.settings;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ============================================================================
-- ANALYTICS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Analytics are publicly readable" ON public.analytics;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- ============================================================================
-- VERIFICATION QUERIES - Run these to verify everything is set up correctly
-- ============================================================================

SELECT 
  'articles table exists' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'articles') as result
UNION ALL
SELECT 
  'article_images table exists',
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images')
UNION ALL
SELECT 
  'is_draft column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');


-- Only these 3 lines are missing from your existing migration

ALTER TABLE public.articles
  DROP CONSTRAINT IF EXISTS articles_source_url_key;

ALTER TABLE public.articles
  ALTER COLUMN source_url DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_source_url_unique
  ON public.articles(source_url)
  WHERE source_url IS NOT NULL;

-- ============================================================================
-- FIX: Allow anon key to read/write/delete draft articles in admin panel
-- The problem: RLS blocks anon users from seeing is_draft=true articles
-- ============================================================================

-- DROP all existing article policies first
DROP POLICY IF EXISTS "Published articles are publicly readable" ON public.articles;
DROP POLICY IF EXISTS "Admins can read all articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to insert articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to update articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to delete articles" ON public.articles;

-- DROP all existing article_images policies
DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;
DROP POLICY IF EXISTS "Allow admin to insert images" ON public.article_images;
DROP POLICY IF EXISTS "Allow admin to delete images" ON public.article_images;

-- ============================================================================
-- ARTICLES: New policies
-- ============================================================================

-- 1. Anyone can read published articles (public website)
CREATE POLICY "Public can read published articles"
ON public.articles FOR SELECT
USING (is_published = true);

-- 2. Anon key can read ALL articles (needed for admin panel drafts)
CREATE POLICY "Anon can read all articles"
ON public.articles FOR SELECT
USING (true);

-- 3. Anon key can insert articles (needed for generate button)
CREATE POLICY "Anon can insert articles"
ON public.articles FOR INSERT
WITH CHECK (true);

-- 4. Anon key can update articles (needed for publish, notes)
CREATE POLICY "Anon can update articles"
ON public.articles FOR UPDATE
USING (true)
WITH CHECK (true);

-- 5. Anon key can delete articles (needed for bulk delete)
CREATE POLICY "Anon can delete articles"
ON public.articles FOR DELETE
USING (true);

-- ============================================================================
-- ARTICLE_IMAGES: New policies
-- ============================================================================

-- 1. Anyone can read images
CREATE POLICY "Public can read article images"
ON public.article_images FOR SELECT
USING (true);

-- 2. Anon can insert images
CREATE POLICY "Anon can insert article images"
ON public.article_images FOR INSERT
WITH CHECK (true);

-- 3. Anon can delete images
CREATE POLICY "Anon can delete article images"
ON public.article_images FOR DELETE
USING (true);

-- 4. Anon can update images
CREATE POLICY "Anon can update article images"
ON public.article_images FOR UPDATE
USING (true)
WITH CHECK (true);

-- ============================================================================
-- VERIFY: Check all policies are in place
-- ============================================================================
SELECT 
  schemaname,
  tablename,
  policyname,
  cmd
FROM pg_policies
WHERE tablename IN ('articles', 'article_images')
ORDER BY tablename, cmd;


ALTER TABLE article_images
ADD COLUMN IF NOT EXISTS photographer      TEXT,
ADD COLUMN IF NOT EXISTS photographer_url  TEXT,
ADD COLUMN IF NOT EXISTS image_source      TEXT,
ADD COLUMN IF NOT EXISTS wiki_attribution  TEXT,
ADD COLUMN IF NOT EXISTS wiki_license      TEXT,
ADD COLUMN IF NOT EXISTS wiki_license_url  TEXT;


-- ============================================================================
-- HISTORY-ONLY MIGRATION
-- Converts your news platform into a pure history content site.
-- Run this in Supabase SQL Editor AFTER your existing migration.
-- ============================================================================

-- ── 1. ADD subcategory column to articles ────────────────────────────────────
ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS subcategory TEXT;

CREATE INDEX IF NOT EXISTS idx_articles_subcategory
  ON public.articles(subcategory);

-- ── 2. ADD a check constraint so only valid history subcategories are stored ─
-- (Optional but recommended — remove the DO block if you prefer no constraint)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'articles_subcategory_check'
  ) THEN
    ALTER TABLE public.articles
      ADD CONSTRAINT articles_subcategory_check CHECK (
        subcategory IS NULL OR subcategory IN (
          'ancient-civilizations',
          'medieval-feudal',
          'age-of-exploration',
          'revolutions-politics',
          'world-wars-conflicts',
          'colonial-imperial',
          'human-rights-movements',
          'science-technology',
          'religion-philosophy',
          'cultural-social',
          'economic-trade',
          'military-warfare',
          'regional-history',
          'archaeology-mysteries',
          'famous-figures'
        )
      );
  END IF;
END $$;

-- ── 3. ADD difficulty / era columns (useful for filtering on the frontend) ───
ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS era        TEXT,   -- e.g. 'ancient', 'medieval', 'modern'
  ADD COLUMN IF NOT EXISTS difficulty TEXT;   -- 'known' | 'hidden' | 'both'

-- ── 4. REMOVE the unique constraint on source_url (already nullable in your
--        latest migration, but make sure it is) ───────────────────────────────
ALTER TABLE public.articles
  DROP CONSTRAINT IF EXISTS articles_source_url_key;

ALTER TABLE public.articles
  ALTER COLUMN source_url DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_source_url_unique
  ON public.articles(source_url)
  WHERE source_url IS NOT NULL;

-- ── 5. SETTINGS — seed history category metadata ────────────────────────────
INSERT INTO public.settings (key, value) VALUES
  ('site_mode',        'history'),
  ('site_name',        'Signal History'),
  ('site_tagline',     'The history they taught you — and the history they buried.'),
  ('auto_publish_score', '7.5'),
  ('history_categories', '[
    {"id":"ancient-civilizations",  "label":"Ancient Civilizations",   "emoji":"🏛️",  "era":"ancient"},
    {"id":"medieval-feudal",        "label":"Medieval & Feudal",        "emoji":"⚔️",  "era":"medieval"},
    {"id":"age-of-exploration",     "label":"Age of Exploration",       "emoji":"🧭",  "era":"early-modern"},
    {"id":"revolutions-politics",   "label":"Revolutions & Politics",   "emoji":"✊",  "era":"modern"},
    {"id":"world-wars-conflicts",   "label":"World Wars & Conflicts",   "emoji":"🎖️",  "era":"modern"},
    {"id":"colonial-imperial",      "label":"Colonial & Imperial",      "emoji":"🌐",  "era":"modern"},
    {"id":"human-rights-movements", "label":"Human Rights Movements",   "emoji":"🕊️",  "era":"modern"},
    {"id":"science-technology",     "label":"Science & Technology",     "emoji":"🔬",  "era":"all"},
    {"id":"religion-philosophy",    "label":"Religion & Philosophy",    "emoji":"📿",  "era":"all"},
    {"id":"cultural-social",        "label":"Cultural & Social",        "emoji":"🎭",  "era":"all"},
    {"id":"economic-trade",         "label":"Economic & Trade",         "emoji":"🏺",  "era":"all"},
    {"id":"military-warfare",       "label":"Military & Warfare",       "emoji":"🗡️",  "era":"all"},
    {"id":"regional-history",       "label":"Regional History",         "emoji":"🗺️",  "era":"all"},
    {"id":"archaeology-mysteries",  "label":"Archaeology & Mysteries",  "emoji":"🔍",  "era":"all"},
    {"id":"famous-figures",         "label":"Famous Figures & Leaders", "emoji":"👑",  "era":"all"}
  ]')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

-- ── 6. VERIFICATION ──────────────────────────────────────────────────────────
SELECT
  'subcategory column'  AS check_item,
  EXISTS (SELECT 1 FROM information_schema.columns
          WHERE table_name = 'articles' AND column_name = 'subcategory') AS result
UNION ALL SELECT
  'era column',
  EXISTS (SELECT 1 FROM information_schema.columns
          WHERE table_name = 'articles' AND column_name = 'era')
UNION ALL SELECT
  'difficulty column',
  EXISTS (SELECT 1 FROM information_schema.columns
          WHERE table_name = 'articles' AND column_name = 'difficulty')
UNION ALL SELECT
  'site_mode setting',
  EXISTS (SELECT 1 FROM public.settings WHERE key = 'site_mode');


CREATE TABLE IF NOT EXISTS public.topic_registry (
  id           BIGSERIAL PRIMARY KEY,
  subcategory  TEXT NOT NULL,
  topic_key    TEXT NOT NULL,
  title        TEXT,
  article_id   BIGINT REFERENCES public.articles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE(subcategory, topic_key)
);

CREATE INDEX idx_topic_registry_subcategory 
  ON public.topic_registry(subcategory);

ALTER TABLE public.topic_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Topic registry is publicly readable"
  ON public.topic_registry FOR SELECT USING (true);

CREATE POLICY "Anon can insert topic registry"
  ON public.topic_registry FOR INSERT WITH CHECK (true);


-- ============================================================================
-- TOPIC REGISTRY — safe re-run version
-- Drops existing policies before recreating to avoid "already exists" errors
-- ============================================================================

-- Table (IF NOT EXISTS is safe to re-run)
CREATE TABLE IF NOT EXISTS public.topic_registry (
  id           BIGSERIAL PRIMARY KEY,
  subcategory  TEXT NOT NULL,
  topic_key    TEXT NOT NULL,
  title        TEXT,
  article_id   BIGINT REFERENCES public.articles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE(subcategory, topic_key)
);

-- Indexes (IF NOT EXISTS is safe to re-run)
CREATE INDEX IF NOT EXISTS idx_topic_registry_subcategory ON public.topic_registry(subcategory);
CREATE INDEX IF NOT EXISTS idx_topic_registry_key         ON public.topic_registry(topic_key);
CREATE INDEX IF NOT EXISTS idx_topic_registry_article_id  ON public.topic_registry(article_id);

-- RLS
ALTER TABLE public.topic_registry ENABLE ROW LEVEL SECURITY;

-- Drop first so re-runs never fail with "already exists"
DROP POLICY IF EXISTS "Topic registry is publicly readable" ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can insert topic registry"      ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can update topic registry"      ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can delete topic registry"      ON public.topic_registry;

CREATE POLICY "Topic registry is publicly readable"
  ON public.topic_registry FOR SELECT USING (true);

CREATE POLICY "Anon can insert topic registry"
  ON public.topic_registry FOR INSERT WITH CHECK (true);

CREATE POLICY "Anon can update topic registry"
  ON public.topic_registry FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Anon can delete topic registry"
  ON public.topic_registry FOR DELETE USING (true);

-- Backfill existing history articles into the registry.
-- ON CONFLICT DO NOTHING makes this safe to re-run any number of times.
INSERT INTO public.topic_registry (subcategory, topic_key, title, article_id)
SELECT
  COALESCE(subcategory, 'unknown') AS subcategory,
  array_to_string(
    ARRAY(
      SELECT word FROM unnest(
        string_to_array(
          regexp_replace(
            regexp_replace(lower(title), '[^a-z0-9 ]', '', 'g'),
            '\s+', ' ', 'g'
          ),
          ' '
        )
      ) AS word
      WHERE length(word) > 3
      ORDER BY word
      LIMIT 6
    ),
    '-'
  ) AS topic_key,
  title,
  id AS article_id
FROM public.articles
WHERE category = 'history'
  AND title IS NOT NULL
  AND title != ''
ON CONFLICT (subcategory, topic_key) DO NOTHING;

-- Verify
SELECT
  'topic_registry table' AS check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'topic_registry') AS result
UNION ALL
SELECT 'row count',      (SELECT COUNT(*) FROM public.topic_registry) > 0
UNION ALL
SELECT 'policies count', (SELECT COUNT(*) FROM pg_policies WHERE tablename = 'topic_registry') = 4;


-- ============================================================================
-- SCHEDULE SETTINGS — controls when cron jobs run
-- Run in Supabase SQL Editor
-- ============================================================================

-- Seed default schedule settings into the existing settings table
INSERT INTO public.settings (key, value) VALUES
  ('schedule_enabled',          'true'),
  ('schedule_hour_utc',         '2'),       -- 2 AM UTC = 7:30 AM IST
  ('schedule_articles_per_cat', '2'),
  ('schedule_last_run',         ''),
  ('schedule_next_run',         ''),
  ('schedule_status',           'idle')     -- 'idle' | 'running' | 'error'
ON CONFLICT (key) DO NOTHING;

-- Verify
SELECT key, value FROM public.settings
WHERE key LIKE 'schedule_%'
ORDER BY key;


CREATE TABLE topic_pool (
  id            BIGSERIAL PRIMARY KEY,
  subcategory   TEXT NOT NULL,
  topic         TEXT NOT NULL,
  topic_key     TEXT NOT NULL,
  is_used       BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(subcategory, topic_key)
);

-- Index for fast querying of unused topics per subcategory
CREATE INDEX idx_topic_pool_subcategory_unused 
  ON topic_pool(subcategory, is_used) 
  WHERE is_used = false;

-- Add bulk scheduler settings to the settings table
INSERT INTO public.settings (key, value) VALUES
  ('bulk_schedule_enabled',  'false'),
  ('bulk_schedule_hour_utc', '3'),
  ('bulk_schedule_status',   'idle'),
  ('bulk_schedule_last_run', ''),
  ('bulk_schedule_next_run', '')
ON CONFLICT (key) DO NOTHING;

-- Verify
SELECT key, value FROM public.settings
WHERE key LIKE 'bulk_%'
ORDER BY key;


-- Allow anon to update settings (needed for admin panel scheduler)
DROP POLICY IF EXISTS "Anon can update settings" ON public.settings;
DROP POLICY IF EXISTS "Anon can insert settings" ON public.settings;
DROP POLICY IF EXISTS "Anon can upsert settings" ON public.settings;

CREATE POLICY "Anon can upsert settings"
  ON public.settings FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Anon can update settings"
  ON public.settings FOR UPDATE
  USING (true)
  WITH CHECK (true);

SELECT policyname, cmd FROM pg_policies WHERE tablename = 'settings';

-- Enable RLS on topic_pool (may already be enabled)
ALTER TABLE public.topic_pool ENABLE ROW LEVEL SECURITY;

-- Drop if exists to avoid conflicts
DROP POLICY IF EXISTS "Anon can read topic_pool"   ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can insert topic_pool"  ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can update topic_pool"  ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can delete topic_pool"  ON public.topic_pool;

-- Create full anon access policies
CREATE POLICY "Anon can read topic_pool"
  ON public.topic_pool FOR SELECT USING (true);

CREATE POLICY "Anon can insert topic_pool"
  ON public.topic_pool FOR INSERT WITH CHECK (true);

CREATE POLICY "Anon can update topic_pool"
  ON public.topic_pool FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Anon can delete topic_pool"
  ON public.topic_pool FOR DELETE USING (true);

-- Verify
SELECT policyname, cmd FROM pg_policies WHERE tablename = 'topic_pool';

-- 1. Check if topic_pool has any data at all
SELECT COUNT(*) FROM public.topic_pool;

-- 2. Check what subcategory values exist
SELECT subcategory, COUNT(*) as total, SUM(CASE WHEN is_used = false THEN 1 ELSE 0 END) as unused
FROM public.topic_pool
GROUP BY subcategory
ORDER BY subcategory;

-- 3. Check RLS policies
SELECT policyname, cmd, qual FROM pg_policies WHERE tablename = 'topic_pool';

-- 4. Check if RLS is enabled
SELECT relname, relrowsecurity FROM pg_class WHERE relname = 'topic_pool';