-- ARTICLES TABLE
CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT NOT NULL UNIQUE,
    source_name     TEXT NOT NULL,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false
);

CREATE INDEX idx_articles_category ON public.articles(category);
CREATE INDEX idx_articles_score ON public.articles(score);
CREATE INDEX idx_articles_published_date ON public.articles(published_date);
CREATE INDEX idx_articles_is_published ON public.articles(is_published);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- UPDATE TIMESTAMP TRIGGER
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_settings_updated_at
BEFORE UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- Supabase Migration: Add article images support (updated - skips duplicates) yes

-- Create article_images table to store multiple images per article
CREATE TABLE IF NOT EXISTS public.article_images (
  id BIGSERIAL PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  alt_text TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  width INTEGER DEFAULT 1200,
  height INTEGER,
  size_kb INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for article_images
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS on article_images
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for article_images
-- Drop existing policies if they exist (optional - comment out if not needed)
-- DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
-- DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Add new columns to articles table (IF NOT EXISTS)
ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS is_draft BOOLEAN DEFAULT TRUE;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS admin_notes TEXT;

ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS scheduled_publish_date TIMESTAMP WITH TIME ZONE;

-- Create index for is_draft (IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);

-- Add comment
COMMENT ON TABLE article_images IS 'Stores multiple images for each article - supports 4-5 images per article at 1200px minimum width';

-- Verify migration
SELECT 
  'article_images table' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images') as exists
UNION ALL
SELECT 
  'is_draft column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');


-- COMPLETE DATABASE MIGRATION FOR ORIGINAL CONTENT SYSTEM
-- Run this in Supabase SQL Editor
-- FIXED: Removed IF NOT EXISTS from CREATE POLICY (not supported)

-- ============================================================================
-- ARTICLES TABLE - Updated for original content + image support
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.articles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    title           TEXT NOT NULL,
    source_url      TEXT,
    source_name     TEXT,
    summary         TEXT NOT NULL,
    raw_content     TEXT,
    category        TEXT NOT NULL,
    score           DECIMAL(3,1),
    image_url       TEXT,
    published_date  TIMESTAMPTZ NOT NULL,
    is_published    BOOLEAN DEFAULT false,
    is_draft        BOOLEAN DEFAULT true,
    admin_notes     TEXT,
    scheduled_publish_date TIMESTAMPTZ
);

-- Create indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_articles_category ON public.articles(category);
CREATE INDEX IF NOT EXISTS idx_articles_score ON public.articles(score);
CREATE INDEX IF NOT EXISTS idx_articles_published_date ON public.articles(published_date);
CREATE INDEX IF NOT EXISTS idx_articles_is_published ON public.articles(is_published);
CREATE INDEX IF NOT EXISTS idx_articles_is_draft ON public.articles(is_draft);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON public.articles(created_at);

-- Enable Row Level Security
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Published articles are publicly readable" ON public.articles;
DROP POLICY IF EXISTS "Admins can read all articles" ON public.articles;

-- RLS Policy: Anyone can read published articles
CREATE POLICY "Published articles are publicly readable"
ON public.articles FOR SELECT
USING (is_published = true);

-- RLS Policy: Authenticated users (admin) can read all articles
CREATE POLICY "Admins can read all articles"
ON public.articles FOR SELECT
USING (auth.role() = 'authenticated');

-- Update trigger for updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Drop trigger if exists, then create
DROP TRIGGER IF EXISTS update_articles_updated_at ON public.articles;
CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON public.articles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- ARTICLE_IMAGES TABLE - For storing multiple images per article
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.article_images (
  id              BIGSERIAL PRIMARY KEY,
  article_id      BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  image_url       TEXT NOT NULL,
  alt_text        TEXT,
  position        INTEGER NOT NULL DEFAULT 0,
  width           INTEGER DEFAULT 1200,
  height          INTEGER,
  size_kb         INTEGER,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_article_images_article_id ON public.article_images(article_id);
CREATE INDEX IF NOT EXISTS idx_article_images_position ON public.article_images(position);

-- Enable RLS
ALTER TABLE public.article_images ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;

-- RLS Policies
CREATE POLICY "Allow public read access to article_images"
  ON public.article_images
  FOR SELECT
  USING (true);

CREATE POLICY "Allow authenticated users to manage images"
  ON public.article_images
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Update trigger for article_images
DROP TRIGGER IF EXISTS update_article_images_updated_at ON public.article_images;
CREATE TRIGGER update_article_images_updated_at
BEFORE UPDATE ON public.article_images
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- SETTINGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Settings are publicly readable" ON public.settings;

CREATE POLICY "Settings are publicly readable"
ON public.settings FOR SELECT
USING (true);

-- ============================================================================
-- ANALYTICS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.analytics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    page_views      INTEGER DEFAULT 0,
    unique_visitors INTEGER DEFAULT 0,
    ad_revenue      DECIMAL(10,2) DEFAULT 0
);

ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Analytics are publicly readable" ON public.analytics;

CREATE POLICY "Analytics are publicly readable"
ON public.analytics FOR SELECT
USING (true);

-- ============================================================================
-- VERIFICATION QUERIES - Run these to verify everything is set up correctly
-- ============================================================================

SELECT 
  'articles table exists' as check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'articles') as result
UNION ALL
SELECT 
  'article_images table exists',
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'article_images')
UNION ALL
SELECT 
  'is_draft column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_draft')
UNION ALL
SELECT 
  'admin_notes column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'admin_notes')
UNION ALL
SELECT 
  'scheduled_publish_date column exists',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'scheduled_publish_date');


-- Only these 3 lines are missing from your existing migration

ALTER TABLE public.articles
  DROP CONSTRAINT IF EXISTS articles_source_url_key;

ALTER TABLE public.articles
  ALTER COLUMN source_url DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_source_url_unique
  ON public.articles(source_url)
  WHERE source_url IS NOT NULL;

-- ============================================================================
-- FIX: Allow anon key to read/write/delete draft articles in admin panel
-- The problem: RLS blocks anon users from seeing is_draft=true articles
-- ============================================================================

-- DROP all existing article policies first
DROP POLICY IF EXISTS "Published articles are publicly readable" ON public.articles;
DROP POLICY IF EXISTS "Admins can read all articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to insert articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to update articles" ON public.articles;
DROP POLICY IF EXISTS "Allow admin to delete articles" ON public.articles;

-- DROP all existing article_images policies
DROP POLICY IF EXISTS "Allow public read access to article_images" ON public.article_images;
DROP POLICY IF EXISTS "Allow authenticated users to manage images" ON public.article_images;
DROP POLICY IF EXISTS "Allow admin to insert images" ON public.article_images;
DROP POLICY IF EXISTS "Allow admin to delete images" ON public.article_images;

-- ============================================================================
-- ARTICLES: New policies
-- ============================================================================

-- 1. Anyone can read published articles (public website)
CREATE POLICY "Public can read published articles"
ON public.articles FOR SELECT
USING (is_published = true);

-- 2. Anon key can read ALL articles (needed for admin panel drafts)
CREATE POLICY "Anon can read all articles"
ON public.articles FOR SELECT
USING (true);

-- 3. Anon key can insert articles (needed for generate button)
CREATE POLICY "Anon can insert articles"
ON public.articles FOR INSERT
WITH CHECK (true);

-- 4. Anon key can update articles (needed for publish, notes)
CREATE POLICY "Anon can update articles"
ON public.articles FOR UPDATE
USING (true)
WITH CHECK (true);

-- 5. Anon key can delete articles (needed for bulk delete)
CREATE POLICY "Anon can delete articles"
ON public.articles FOR DELETE
USING (true);

-- ============================================================================
-- ARTICLE_IMAGES: New policies
-- ============================================================================

-- 1. Anyone can read images
CREATE POLICY "Public can read article images"
ON public.article_images FOR SELECT
USING (true);

-- 2. Anon can insert images
CREATE POLICY "Anon can insert article images"
ON public.article_images FOR INSERT
WITH CHECK (true);

-- 3. Anon can delete images
CREATE POLICY "Anon can delete article images"
ON public.article_images FOR DELETE
USING (true);

-- 4. Anon can update images
CREATE POLICY "Anon can update article images"
ON public.article_images FOR UPDATE
USING (true)
WITH CHECK (true);

-- ============================================================================
-- VERIFY: Check all policies are in place
-- ============================================================================
SELECT 
  schemaname,
  tablename,
  policyname,
  cmd
FROM pg_policies
WHERE tablename IN ('articles', 'article_images')
ORDER BY tablename, cmd;


ALTER TABLE article_images
ADD COLUMN IF NOT EXISTS photographer      TEXT,
ADD COLUMN IF NOT EXISTS photographer_url  TEXT,
ADD COLUMN IF NOT EXISTS image_source      TEXT,
ADD COLUMN IF NOT EXISTS wiki_attribution  TEXT,
ADD COLUMN IF NOT EXISTS wiki_license      TEXT,
ADD COLUMN IF NOT EXISTS wiki_license_url  TEXT;


-- ============================================================================
-- HISTORY-ONLY MIGRATION
-- Converts your news platform into a pure history content site.
-- Run this in Supabase SQL Editor AFTER your existing migration.
-- ============================================================================

-- ── 1. ADD subcategory column to articles ────────────────────────────────────
ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS subcategory TEXT;

CREATE INDEX IF NOT EXISTS idx_articles_subcategory
  ON public.articles(subcategory);

-- ── 2. ADD a check constraint so only valid history subcategories are stored ─
-- (Optional but recommended — remove the DO block if you prefer no constraint)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'articles_subcategory_check'
  ) THEN
    ALTER TABLE public.articles
      ADD CONSTRAINT articles_subcategory_check CHECK (
        subcategory IS NULL OR subcategory IN (
          'ancient-civilizations',
          'medieval-feudal',
          'age-of-exploration',
          'revolutions-politics',
          'world-wars-conflicts',
          'colonial-imperial',
          'human-rights-movements',
          'science-technology',
          'religion-philosophy',
          'cultural-social',
          'economic-trade',
          'military-warfare',
          'regional-history',
          'archaeology-mysteries',
          'famous-figures'
        )
      );
  END IF;
END $$;

-- ── 3. ADD difficulty / era columns (useful for filtering on the frontend) ───
ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS era        TEXT,   -- e.g. 'ancient', 'medieval', 'modern'
  ADD COLUMN IF NOT EXISTS difficulty TEXT;   -- 'known' | 'hidden' | 'both'

-- ── 4. REMOVE the unique constraint on source_url (already nullable in your
--        latest migration, but make sure it is) ───────────────────────────────
ALTER TABLE public.articles
  DROP CONSTRAINT IF EXISTS articles_source_url_key;

ALTER TABLE public.articles
  ALTER COLUMN source_url DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_source_url_unique
  ON public.articles(source_url)
  WHERE source_url IS NOT NULL;

-- ── 5. SETTINGS — seed history category metadata ────────────────────────────
INSERT INTO public.settings (key, value) VALUES
  ('site_mode',        'history'),
  ('site_name',        'Signal History'),
  ('site_tagline',     'The history they taught you — and the history they buried.'),
  ('auto_publish_score', '7.5'),
  ('history_categories', '[
    {"id":"ancient-civilizations",  "label":"Ancient Civilizations",   "emoji":"🏛️",  "era":"ancient"},
    {"id":"medieval-feudal",        "label":"Medieval & Feudal",        "emoji":"⚔️",  "era":"medieval"},
    {"id":"age-of-exploration",     "label":"Age of Exploration",       "emoji":"🧭",  "era":"early-modern"},
    {"id":"revolutions-politics",   "label":"Revolutions & Politics",   "emoji":"✊",  "era":"modern"},
    {"id":"world-wars-conflicts",   "label":"World Wars & Conflicts",   "emoji":"🎖️",  "era":"modern"},
    {"id":"colonial-imperial",      "label":"Colonial & Imperial",      "emoji":"🌐",  "era":"modern"},
    {"id":"human-rights-movements", "label":"Human Rights Movements",   "emoji":"🕊️",  "era":"modern"},
    {"id":"science-technology",     "label":"Science & Technology",     "emoji":"🔬",  "era":"all"},
    {"id":"religion-philosophy",    "label":"Religion & Philosophy",    "emoji":"📿",  "era":"all"},
    {"id":"cultural-social",        "label":"Cultural & Social",        "emoji":"🎭",  "era":"all"},
    {"id":"economic-trade",         "label":"Economic & Trade",         "emoji":"🏺",  "era":"all"},
    {"id":"military-warfare",       "label":"Military & Warfare",       "emoji":"🗡️",  "era":"all"},
    {"id":"regional-history",       "label":"Regional History",         "emoji":"🗺️",  "era":"all"},
    {"id":"archaeology-mysteries",  "label":"Archaeology & Mysteries",  "emoji":"🔍",  "era":"all"},
    {"id":"famous-figures",         "label":"Famous Figures & Leaders", "emoji":"👑",  "era":"all"}
  ]')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

-- ── 6. VERIFICATION ──────────────────────────────────────────────────────────
SELECT
  'subcategory column'  AS check_item,
  EXISTS (SELECT 1 FROM information_schema.columns
          WHERE table_name = 'articles' AND column_name = 'subcategory') AS result
UNION ALL SELECT
  'era column',
  EXISTS (SELECT 1 FROM information_schema.columns
          WHERE table_name = 'articles' AND column_name = 'era')
UNION ALL SELECT
  'difficulty column',
  EXISTS (SELECT 1 FROM information_schema.columns
          WHERE table_name = 'articles' AND column_name = 'difficulty')
UNION ALL SELECT
  'site_mode setting',
  EXISTS (SELECT 1 FROM public.settings WHERE key = 'site_mode');


CREATE TABLE IF NOT EXISTS public.topic_registry (
  id           BIGSERIAL PRIMARY KEY,
  subcategory  TEXT NOT NULL,
  topic_key    TEXT NOT NULL,
  title        TEXT,
  article_id   BIGINT REFERENCES public.articles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE(subcategory, topic_key)
);

CREATE INDEX idx_topic_registry_subcategory 
  ON public.topic_registry(subcategory);

ALTER TABLE public.topic_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Topic registry is publicly readable"
  ON public.topic_registry FOR SELECT USING (true);

CREATE POLICY "Anon can insert topic registry"
  ON public.topic_registry FOR INSERT WITH CHECK (true);


-- ============================================================================
-- TOPIC REGISTRY — safe re-run version
-- Drops existing policies before recreating to avoid "already exists" errors
-- ============================================================================

-- Table (IF NOT EXISTS is safe to re-run)
CREATE TABLE IF NOT EXISTS public.topic_registry (
  id           BIGSERIAL PRIMARY KEY,
  subcategory  TEXT NOT NULL,
  topic_key    TEXT NOT NULL,
  title        TEXT,
  article_id   BIGINT REFERENCES public.articles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE(subcategory, topic_key)
);

-- Indexes (IF NOT EXISTS is safe to re-run)
CREATE INDEX IF NOT EXISTS idx_topic_registry_subcategory ON public.topic_registry(subcategory);
CREATE INDEX IF NOT EXISTS idx_topic_registry_key         ON public.topic_registry(topic_key);
CREATE INDEX IF NOT EXISTS idx_topic_registry_article_id  ON public.topic_registry(article_id);

-- RLS
ALTER TABLE public.topic_registry ENABLE ROW LEVEL SECURITY;

-- Drop first so re-runs never fail with "already exists"
DROP POLICY IF EXISTS "Topic registry is publicly readable" ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can insert topic registry"      ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can update topic registry"      ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can delete topic registry"      ON public.topic_registry;

CREATE POLICY "Topic registry is publicly readable"
  ON public.topic_registry FOR SELECT USING (true);

CREATE POLICY "Anon can insert topic registry"
  ON public.topic_registry FOR INSERT WITH CHECK (true);

CREATE POLICY "Anon can update topic registry"
  ON public.topic_registry FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Anon can delete topic registry"
  ON public.topic_registry FOR DELETE USING (true);

-- Backfill existing history articles into the registry.
-- ON CONFLICT DO NOTHING makes this safe to re-run any number of times.
INSERT INTO public.topic_registry (subcategory, topic_key, title, article_id)
SELECT
  COALESCE(subcategory, 'unknown') AS subcategory,
  array_to_string(
    ARRAY(
      SELECT word FROM unnest(
        string_to_array(
          regexp_replace(
            regexp_replace(lower(title), '[^a-z0-9 ]', '', 'g'),
            '\s+', ' ', 'g'
          ),
          ' '
        )
      ) AS word
      WHERE length(word) > 3
      ORDER BY word
      LIMIT 6
    ),
    '-'
  ) AS topic_key,
  title,
  id AS article_id
FROM public.articles
WHERE category = 'history'
  AND title IS NOT NULL
  AND title != ''
ON CONFLICT (subcategory, topic_key) DO NOTHING;

-- Verify
SELECT
  'topic_registry table' AS check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'topic_registry') AS result
UNION ALL
SELECT 'row count',      (SELECT COUNT(*) FROM public.topic_registry) > 0
UNION ALL
SELECT 'policies count', (SELECT COUNT(*) FROM pg_policies WHERE tablename = 'topic_registry') = 4;


-- ============================================================================
-- SCHEDULE SETTINGS — controls when cron jobs run
-- Run in Supabase SQL Editor
-- ============================================================================

-- Seed default schedule settings into the existing settings table
INSERT INTO public.settings (key, value) VALUES
  ('schedule_enabled',          'true'),
  ('schedule_hour_utc',         '2'),       -- 2 AM UTC = 7:30 AM IST
  ('schedule_articles_per_cat', '2'),
  ('schedule_last_run',         ''),
  ('schedule_next_run',         ''),
  ('schedule_status',           'idle')     -- 'idle' | 'running' | 'error'
ON CONFLICT (key) DO NOTHING;

-- Verify
SELECT key, value FROM public.settings
WHERE key LIKE 'schedule_%'
ORDER BY key;


CREATE TABLE topic_pool (
  id            BIGSERIAL PRIMARY KEY,
  subcategory   TEXT NOT NULL,
  topic         TEXT NOT NULL,
  topic_key     TEXT NOT NULL,
  is_used       BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(subcategory, topic_key)
);

-- Index for fast querying of unused topics per subcategory
CREATE INDEX idx_topic_pool_subcategory_unused 
  ON topic_pool(subcategory, is_used) 
  WHERE is_used = false;

-- Add bulk scheduler settings to the settings table
INSERT INTO public.settings (key, value) VALUES
  ('bulk_schedule_enabled',  'false'),
  ('bulk_schedule_hour_utc', '3'),
  ('bulk_schedule_status',   'idle'),
  ('bulk_schedule_last_run', ''),
  ('bulk_schedule_next_run', '')
ON CONFLICT (key) DO NOTHING;

-- Verify
SELECT key, value FROM public.settings
WHERE key LIKE 'bulk_%'
ORDER BY key;


-- Allow anon to update settings (needed for admin panel scheduler)
DROP POLICY IF EXISTS "Anon can update settings" ON public.settings;
DROP POLICY IF EXISTS "Anon can insert settings" ON public.settings;
DROP POLICY IF EXISTS "Anon can upsert settings" ON public.settings;

CREATE POLICY "Anon can upsert settings"
  ON public.settings FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Anon can update settings"
  ON public.settings FOR UPDATE
  USING (true)
  WITH CHECK (true);

SELECT policyname, cmd FROM pg_policies WHERE tablename = 'settings';

-- Enable RLS on topic_pool (may already be enabled)
ALTER TABLE public.topic_pool ENABLE ROW LEVEL SECURITY;

-- Drop if exists to avoid conflicts
DROP POLICY IF EXISTS "Anon can read topic_pool"   ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can insert topic_pool"  ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can update topic_pool"  ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can delete topic_pool"  ON public.topic_pool;

-- Create full anon access policies
CREATE POLICY "Anon can read topic_pool"
  ON public.topic_pool FOR SELECT USING (true);

CREATE POLICY "Anon can insert topic_pool"
  ON public.topic_pool FOR INSERT WITH CHECK (true);

CREATE POLICY "Anon can update topic_pool"
  ON public.topic_pool FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Anon can delete topic_pool"
  ON public.topic_pool FOR DELETE USING (true);

-- Verify
SELECT policyname, cmd FROM pg_policies WHERE tablename = 'topic_pool';

-- 1. Check if topic_pool has any data at all
SELECT COUNT(*) FROM public.topic_pool;

-- 2. Check what subcategory values exist
SELECT subcategory, COUNT(*) as total, SUM(CASE WHEN is_used = false THEN 1 ELSE 0 END) as unused
FROM public.topic_pool
GROUP BY subcategory
ORDER BY subcategory;

-- 3. Check RLS policies
SELECT policyname, cmd, qual FROM pg_policies WHERE tablename = 'topic_pool';

-- 4. Check if RLS is enabled
SELECT relname, relrowsecurity FROM pg_class WHERE relname = 'topic_pool';

-- 1. Add slug column
ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS slug TEXT;

-- 2. Create unique index
CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_slug
  ON public.articles(slug)
  WHERE slug IS NOT NULL;

-- 3. Backfill slugs for all existing articles from their titles
UPDATE public.articles
SET slug = lower(
  regexp_replace(
    regexp_replace(
      regexp_replace(title, '[^a-zA-Z0-9\s-]', '', 'g'),  -- remove special chars
      '\s+', '-', 'g'                                        -- spaces to hyphens
    ),
    '-+', '-', 'g'                                           -- collapse multiple hyphens
  )
)
WHERE slug IS NULL AND title IS NOT NULL;

-- 4. Verify
SELECT id, title, slug FROM public.articles LIMIT 10;


-- Step 1: Drop the existing constraint
ALTER TABLE public.articles
  DROP CONSTRAINT IF EXISTS articles_subcategory_check;

-- Step 2: Re-add with all 17 subcategories
ALTER TABLE public.articles
  ADD CONSTRAINT articles_subcategory_check CHECK (
    subcategory IS NULL OR subcategory IN (
      'ancient-civilizations',
      'medieval-feudal',
      'age-of-exploration',
      'revolutions-politics',
      'world-wars-conflicts',
      'colonial-imperial',
      'human-rights-movements',
      'science-technology',
      'religion-philosophy',
      'cultural-social',
      'economic-trade',
      'military-warfare',
      'regional-history',
      'archaeology-mysteries',
      'famous-figures',
      'beyond-human-limits',
      'historys-unsung-heroes'
    )
  );

-- Step 3: Update history_categories setting
UPDATE public.settings
SET value = '[
  {"id":"ancient-civilizations",  "label":"Ancient Civilizations",   "emoji":"🏛️",  "era":"ancient"},
  {"id":"medieval-feudal",        "label":"Medieval & Feudal",        "emoji":"⚔️",  "era":"medieval"},
  {"id":"age-of-exploration",     "label":"Age of Exploration",       "emoji":"🧭",  "era":"early-modern"},
  {"id":"revolutions-politics",   "label":"Revolutions & Politics",   "emoji":"✊",  "era":"modern"},
  {"id":"world-wars-conflicts",   "label":"World Wars & Conflicts",   "emoji":"🎖️",  "era":"modern"},
  {"id":"colonial-imperial",      "label":"Colonial & Imperial",      "emoji":"🌐",  "era":"modern"},
  {"id":"human-rights-movements", "label":"Human Rights Movements",   "emoji":"🕊️",  "era":"modern"},
  {"id":"science-technology",     "label":"Science & Technology",     "emoji":"🔬",  "era":"all"},
  {"id":"religion-philosophy",    "label":"Religion & Philosophy",    "emoji":"📿",  "era":"all"},
  {"id":"cultural-social",        "label":"Cultural & Social",        "emoji":"🎭",  "era":"all"},
  {"id":"economic-trade",         "label":"Economic & Trade",         "emoji":"🏺",  "era":"all"},
  {"id":"military-warfare",       "label":"Military & Warfare",       "emoji":"🗡️",  "era":"all"},
  {"id":"regional-history",       "label":"Regional History",         "emoji":"🗺️",  "era":"all"},
  {"id":"archaeology-mysteries",  "label":"Archaeology & Mysteries",  "emoji":"🔍",  "era":"all"},
  {"id":"famous-figures",         "label":"Famous Figures & Leaders", "emoji":"👑",  "era":"all"},
  {"id":"beyond-human-limits",    "label":"Beyond Human Limits",      "emoji":"🚀",  "era":"all"},
  {"id":"historys-unsung-heroes", "label":"Historys Unsung Heroes",   "emoji":"⭐",  "era":"all"}
]',
updated_at = now()
WHERE key = 'history_categories';

-- Step 4: Verify
SELECT value FROM public.settings WHERE key = 'history_categories';
SELECT conname FROM pg_constraint WHERE conname = 'articles_subcategory_check';


-- ============================================================================
-- HIDDEN FACTS — SCALE MIGRATION
-- Purpose : Security hardening + performance indexes + scalability prep
-- Safe    : Every statement uses IF NOT EXISTS / DROP IF EXISTS / OR REPLACE
-- Order   : Run top to bottom — sections are labelled.
-- ============================================================================


-- ============================================================================
-- SECTION 1 · SECURITY — Admin whitelist table
-- ----------------------------------------------------------------------------
-- Your current RLS lets the anon key INSERT/UPDATE/DELETE everything.
-- We fix this with an admin_sessions table. Your Next.js admin panel should
-- call check_is_admin() before every mutating operation.
-- Until you wire in proper auth (Supabase Auth / NextAuth), the secret is
-- stored in settings. Change 'CHANGE_ME_TO_A_LONG_RANDOM_SECRET' below.
-- ============================================================================

-- Admin session tokens (hashed) — one row per active admin browser session
CREATE TABLE IF NOT EXISTS public.admin_sessions (
  id          BIGSERIAL PRIMARY KEY,
  token_hash  TEXT NOT NULL UNIQUE,        -- SHA-256 of the raw token
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '12 hours',
  ip_address  TEXT
);

ALTER TABLE public.admin_sessions ENABLE ROW LEVEL SECURITY;

-- No anon reads — only service role (server-side Next.js) may touch this
DROP POLICY IF EXISTS "No public access to admin_sessions" ON public.admin_sessions;
CREATE POLICY "No public access to admin_sessions"
  ON public.admin_sessions FOR ALL
  USING (false);

-- Function the frontend can call via RPC to validate a session
CREATE OR REPLACE FUNCTION public.check_is_admin(p_token TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.admin_sessions
    WHERE token_hash = encode(sha256(p_token::bytea), 'hex')
      AND expires_at > now()
  );
END;
$$;


-- ============================================================================
-- SECTION 2 · SECURITY — Tighten RLS on every table
-- ----------------------------------------------------------------------------
-- Current state : anon can INSERT/UPDATE/DELETE articles, article_images,
--                 settings, topic_pool, topic_registry — no auth required.
-- New state      : reads are still public, writes require check_is_admin().
-- ============================================================================

-- ── articles ────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Public can read published articles"    ON public.articles;
DROP POLICY IF EXISTS "Anon can read all articles"            ON public.articles;
DROP POLICY IF EXISTS "Anon can insert articles"              ON public.articles;
DROP POLICY IF EXISTS "Anon can update articles"              ON public.articles;
DROP POLICY IF EXISTS "Anon can delete articles"              ON public.articles;

-- Anyone can read published articles (your public website)
CREATE POLICY "Public reads published articles"
  ON public.articles FOR SELECT
  USING (is_published = true);

-- Admin reads all (drafts too) — token validated server-side via RPC;
-- for the admin panel Next.js page use the service role key (server only).
-- This policy allows service_role bypass (Supabase default behaviour).

-- Writes require a verified admin session token passed as a claim.
-- In your Next.js admin API routes, use the service role key — not anon.
-- These policies lock out raw anon key abuse from the browser:
CREATE POLICY "Service role can insert articles"
  ON public.articles FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can update articles"
  ON public.articles FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can delete articles"
  ON public.articles FOR DELETE
  USING (auth.role() = 'service_role');


-- ── article_images ───────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Public can read article images"        ON public.article_images;
DROP POLICY IF EXISTS "Anon can insert article images"        ON public.article_images;
DROP POLICY IF EXISTS "Anon can delete article images"        ON public.article_images;
DROP POLICY IF EXISTS "Anon can update article images"        ON public.article_images;

CREATE POLICY "Public reads article images"
  ON public.article_images FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert article_images"
  ON public.article_images FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can update article_images"
  ON public.article_images FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can delete article_images"
  ON public.article_images FOR DELETE
  USING (auth.role() = 'service_role');


-- ── settings ─────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Settings are publicly readable"  ON public.settings;
DROP POLICY IF EXISTS "Anon can upsert settings"        ON public.settings;
DROP POLICY IF EXISTS "Anon can update settings"        ON public.settings;

CREATE POLICY "Public reads settings"
  ON public.settings FOR SELECT
  USING (true);

CREATE POLICY "Service role can upsert settings"
  ON public.settings FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can update settings"
  ON public.settings FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');


-- ── topic_pool ────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Anon can read topic_pool"   ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can insert topic_pool"  ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can update topic_pool"  ON public.topic_pool;
DROP POLICY IF EXISTS "Anon can delete topic_pool"  ON public.topic_pool;

CREATE POLICY "Public reads topic_pool"
  ON public.topic_pool FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert topic_pool"
  ON public.topic_pool FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can update topic_pool"
  ON public.topic_pool FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can delete topic_pool"
  ON public.topic_pool FOR DELETE
  USING (auth.role() = 'service_role');


-- ── topic_registry ────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Topic registry is publicly readable"  ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can insert topic registry"       ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can update topic registry"       ON public.topic_registry;
DROP POLICY IF EXISTS "Anon can delete topic registry"       ON public.topic_registry;

CREATE POLICY "Public reads topic_registry"
  ON public.topic_registry FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert topic_registry"
  ON public.topic_registry FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can update topic_registry"
  ON public.topic_registry FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can delete topic_registry"
  ON public.topic_registry FOR DELETE
  USING (auth.role() = 'service_role');


-- ── analytics ─────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Analytics are publicly readable" ON public.analytics;

CREATE POLICY "Public reads analytics"
  ON public.analytics FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert analytics"
  ON public.analytics FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can update analytics"
  ON public.analytics FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');


-- ============================================================================
-- SECTION 3 · SECURITY — Rate-limit helper table
-- ----------------------------------------------------------------------------
-- Track generation requests per IP to prevent abuse of your Groq quota.
-- Call increment_rate_limit() from a Next.js API route before calling Groq.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.rate_limits (
  id          BIGSERIAL PRIMARY KEY,
  identifier  TEXT NOT NULL,               -- IP address or user ID
  action      TEXT NOT NULL,               -- e.g. 'generate', 'publish'
  window_start TIMESTAMPTZ NOT NULL DEFAULT date_trunc('hour', now()),
  count       INTEGER NOT NULL DEFAULT 1,
  UNIQUE (identifier, action, window_start)
);

ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No public access to rate_limits" ON public.rate_limits;
CREATE POLICY "No public access to rate_limits"
  ON public.rate_limits FOR ALL
  USING (false);

CREATE INDEX IF NOT EXISTS idx_rate_limits_lookup
  ON public.rate_limits (identifier, action, window_start);

CREATE OR REPLACE FUNCTION public.increment_rate_limit(
  p_identifier TEXT,
  p_action     TEXT,
  p_max        INTEGER DEFAULT 20
)
RETURNS BOOLEAN   -- TRUE = allowed, FALSE = blocked
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_window TIMESTAMPTZ := date_trunc('hour', now());
  v_count  INTEGER;
BEGIN
  INSERT INTO public.rate_limits (identifier, action, window_start, count)
  VALUES (p_identifier, p_action, v_window, 1)
  ON CONFLICT (identifier, action, window_start)
  DO UPDATE SET count = rate_limits.count + 1
  RETURNING count INTO v_count;
  RETURN v_count <= p_max;
END;
$$;


-- ============================================================================
-- SECTION 4 · PERFORMANCE — Extensions
-- ============================================================================

-- Full-text search and trigram similarity (fuzzy slug/title matching)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Needed for sha256() in check_is_admin
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================================
-- SECTION 5 · PERFORMANCE — Composite indexes for your actual query patterns
-- ----------------------------------------------------------------------------
-- Every query in your category/[slug]/page.tsx and article/[slug]/page.tsx
-- uses a combination of these columns. Single-column indexes won't be used
-- when Postgres needs to filter on two columns simultaneously.
-- ============================================================================

-- Public homepage / category page: filter by published + category or subcategory,
-- ordered by published_date DESC — this is your highest-traffic query.
CREATE INDEX IF NOT EXISTS idx_articles_pub_subcat_date
  ON public.articles (subcategory, is_published, published_date DESC)
  WHERE is_published = true;

CREATE INDEX IF NOT EXISTS idx_articles_pub_cat_date
  ON public.articles (category, is_published, published_date DESC)
  WHERE is_published = true;

-- Related articles query: subcategory + published + score DESC
CREATE INDEX IF NOT EXISTS idx_articles_pub_subcat_score
  ON public.articles (subcategory, is_published, score DESC NULLS LAST)
  WHERE is_published = true;

-- Admin panel: draft list ordered by created_at DESC
CREATE INDEX IF NOT EXISTS idx_articles_draft_created
  ON public.articles (is_draft, created_at DESC)
  WHERE is_draft = true;

-- Admin panel: subcategory filter combined with draft
CREATE INDEX IF NOT EXISTS idx_articles_draft_subcat_created
  ON public.articles (is_draft, subcategory, created_at DESC)
  WHERE is_draft = true;

-- Slug lookup (your primary article fetch path) — already has unique index,
-- but add a covering index so Postgres doesn't need a heap fetch for slug queries
-- that only need id + is_published.
CREATE INDEX IF NOT EXISTS idx_articles_slug_published
  ON public.articles (slug, is_published)
  WHERE slug IS NOT NULL;

-- topic_pool: the most common admin query — unused topics per subcategory
-- ordered by created_at (FIFO — oldest topics used first)
DROP INDEX IF EXISTS idx_topic_pool_subcategory_unused;
CREATE INDEX IF NOT EXISTS idx_topic_pool_unused_fifo
  ON public.topic_pool (subcategory, is_used, created_at ASC)
  WHERE is_used = false;

-- topic_registry: article_id FK lookups (cascade deletes need this)
CREATE INDEX IF NOT EXISTS idx_topic_registry_article_id
  ON public.topic_registry (article_id)
  WHERE article_id IS NOT NULL;

-- article_images: most queries fetch all images for one article
-- already exists but add a covering index including position
DROP INDEX IF EXISTS idx_article_images_article_id;
CREATE INDEX IF NOT EXISTS idx_article_images_article_position
  ON public.article_images (article_id, position ASC);


-- ============================================================================
-- SECTION 6 · PERFORMANCE — Full-text search index on articles
-- ----------------------------------------------------------------------------
-- This lets you add a /search page later without a separate service.
-- Uses ts_vector over title + summary for fast GIN-indexed FTS queries.
-- Example query: WHERE fts @@ to_tsquery('english', 'rome & empire')
-- ============================================================================

ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS fts tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(summary, '')), 'B')
    ) STORED;

CREATE INDEX IF NOT EXISTS idx_articles_fts
  ON public.articles USING GIN (fts);

-- Trigram index on title for fuzzy/autocomplete search
CREATE INDEX IF NOT EXISTS idx_articles_title_trgm
  ON public.articles USING GIN (title gin_trgm_ops);

-- Trigram index on slug for partial-match slug routing
CREATE INDEX IF NOT EXISTS idx_articles_slug_trgm
  ON public.articles USING GIN (slug gin_trgm_ops)
  WHERE slug IS NOT NULL;


-- ============================================================================
-- SECTION 7 · PERFORMANCE — Materialized view: category article counts
-- ----------------------------------------------------------------------------
-- Your frontend currently has no count display, but when you add it,
-- a live COUNT(*) on the articles table at millions of rows is expensive.
-- This view refreshes in the background without locking reads.
-- Refresh it after every generation run:
--   SELECT refresh_category_counts();
-- ============================================================================

CREATE MATERIALIZED VIEW IF NOT EXISTS public.category_counts AS
SELECT
  subcategory,
  category,
  COUNT(*) FILTER (WHERE is_published = true)  AS published_count,
  COUNT(*) FILTER (WHERE is_draft = true)       AS draft_count,
  COUNT(*)                                       AS total_count,
  MAX(published_date)                            AS latest_published_at
FROM public.articles
GROUP BY subcategory, category;

CREATE UNIQUE INDEX IF NOT EXISTS idx_category_counts_subcat
  ON public.category_counts (subcategory);

CREATE OR REPLACE FUNCTION public.refresh_category_counts()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.category_counts;
END;
$$;

-- RLS: readable by everyone (it's aggregate counts, no PII)
-- Materialized views don't support RLS directly — access is controlled by
-- the calling role. Service role can always refresh.


-- ============================================================================
-- SECTION 8 · PERFORMANCE — Lightweight admin list view
-- ----------------------------------------------------------------------------
-- Your admin panel fetches SELECT * which includes raw_content (can be 10KB+).
-- This view strips it out. Update your admin panel query to use this view.
-- In AdminPanel.tsx change:
--   supabase.from('articles').select('*')
-- to:
--   supabase.from('articles_admin_list').select('*')
-- ============================================================================

CREATE OR REPLACE VIEW public.articles_admin_list AS
SELECT
  id, created_at, updated_at, title, source_url, source_name,
  summary,           -- keep summary (short)
  category, subcategory, score, image_url, published_date,
  is_published, is_draft, admin_notes, scheduled_publish_date,
  era, difficulty, slug,
  -- raw_content deliberately excluded — fetch it separately on article open
  length(coalesce(raw_content, '')) AS content_length_chars
FROM public.articles;


-- ============================================================================
-- SECTION 9 · SCALABILITY — Slug integrity and collision prevention
-- ----------------------------------------------------------------------------
-- Currently slugs are generated in JS and may collide silently.
-- This function generates a guaranteed-unique slug from a title,
-- appending a numeric suffix if the base slug already exists.
-- Call it from your Next.js API route on article creation.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.generate_unique_slug(p_title TEXT, p_exclude_id BIGINT DEFAULT NULL)
RETURNS TEXT
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_base  TEXT;
  v_slug  TEXT;
  v_count INTEGER := 0;
BEGIN
  -- Sanitise: lowercase, remove non-alphanum, collapse hyphens, trim
  v_base := lower(
    regexp_replace(
      regexp_replace(
        regexp_replace(p_title, '[^a-zA-Z0-9\s\-]', '', 'g'),
        '\s+', '-', 'g'
      ),
      '-+', '-', 'g'
    )
  );
  v_base := trim(both '-' from v_base);
  v_base := left(v_base, 80);   -- max 80 chars before suffix
  v_slug := v_base;

  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM public.articles
      WHERE slug = v_slug
        AND (p_exclude_id IS NULL OR id != p_exclude_id)
    ) THEN
      RETURN v_slug;
    END IF;
    v_count := v_count + 1;
    v_slug  := v_base || '-' || v_count;
  END LOOP;
END;
$$;

-- Backfill any articles that ended up with a NULL slug
UPDATE public.articles
SET slug = public.generate_unique_slug(title, id)
WHERE slug IS NULL AND title IS NOT NULL AND title != '';


-- ============================================================================
-- SECTION 10 · SCALABILITY — updated_at on topic_pool (was missing)
-- ============================================================================

ALTER TABLE public.topic_pool
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

DROP TRIGGER IF EXISTS update_topic_pool_updated_at ON public.topic_pool;
CREATE TRIGGER update_topic_pool_updated_at
  BEFORE UPDATE ON public.topic_pool
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- ============================================================================
-- SECTION 11 · SCALABILITY — Soft-delete + archive support
-- ----------------------------------------------------------------------------
-- Instead of hard-deleting articles (which leaves topic_registry orphans),
-- add a deleted_at column. Your bulk-delete UI should set this, not DELETE.
-- Add WHERE deleted_at IS NULL to all your normal queries.
-- Hard deletes can run in a weekly cleanup job.
-- ============================================================================

ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_articles_not_deleted
  ON public.articles (id)
  WHERE deleted_at IS NULL;

-- Safe delete function — marks as deleted, does NOT cascade immediately
CREATE OR REPLACE FUNCTION public.soft_delete_article(p_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.articles
  SET deleted_at = now(), is_published = false, is_draft = false
  WHERE id = p_id AND deleted_at IS NULL;

  -- Unlink from topic_registry (keeps the topic key, just detaches article)
  UPDATE public.topic_registry
  SET article_id = NULL
  WHERE article_id = p_id;
END;
$$;

-- Purge articles soft-deleted more than 30 days ago (run via pg_cron or manually)
CREATE OR REPLACE FUNCTION public.purge_deleted_articles()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_count INTEGER;
BEGIN
  DELETE FROM public.articles
  WHERE deleted_at IS NOT NULL
    AND deleted_at < now() - INTERVAL '30 days'
  ;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;


-- ============================================================================
-- SECTION 12 · SCALABILITY — analytics date uniqueness + index
-- ============================================================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_analytics_date_unique
  ON public.analytics (date);

CREATE INDEX IF NOT EXISTS idx_analytics_date_desc
  ON public.analytics (date DESC);


-- ============================================================================
-- SECTION 13 · SCALABILITY — Row-level limit guard
-- ----------------------------------------------------------------------------
-- Prevents any single query from accidentally returning millions of rows.
-- Supabase already caps at 1000 by default, but this makes it explicit
-- and allows you to configure per-table limits.
-- ============================================================================

-- Set statement_timeout for the anon and authenticated roles
-- (prevents long-running frontend queries from consuming DB connections)
-- Run this as superuser / postgres role:
ALTER ROLE anon          SET statement_timeout = '5s';
ALTER ROLE authenticated SET statement_timeout = '10s';


-- ============================================================================
-- SECTION 14 · HOUSEKEEPING — Verify everything
-- ============================================================================

SELECT
  'admin_sessions table'       AS check_item,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'admin_sessions')  AS ok
UNION ALL SELECT
  'rate_limits table',
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'rate_limits')
UNION ALL SELECT
  'fts column on articles',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'fts')
UNION ALL SELECT
  'deleted_at column on articles',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'deleted_at')
UNION ALL SELECT
  'updated_at on topic_pool',
  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'topic_pool' AND column_name = 'updated_at')
UNION ALL SELECT
  'category_counts matview',
  EXISTS (SELECT 1 FROM pg_matviews WHERE matviewname = 'category_counts')
UNION ALL SELECT
  'articles_admin_list view',
  EXISTS (SELECT 1 FROM information_schema.views WHERE table_name = 'articles_admin_list')
UNION ALL SELECT
  'composite index pub_subcat_date',
  EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_articles_pub_subcat_date')
UNION ALL SELECT
  'full-text GIN index',
  EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_articles_fts')
UNION ALL SELECT
  'pg_trgm extension',
  EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm')
UNION ALL SELECT
  'slug backfill complete',
  NOT EXISTS (SELECT 1 FROM public.articles WHERE slug IS NULL AND title IS NOT NULL)
UNION ALL SELECT
  'check_is_admin function',
  EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'check_is_admin')
ORDER BY check_item;

-- First, check if the view exists and what columns it has
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'articles_admin_list' 
  AND table_schema = 'public'
ORDER BY ordinal_position;

-- Now, let's fix the view by dropping and recreating it with the correct columns
-- Drop the existing view
DROP VIEW IF EXISTS public.articles_admin_list;

-- Recreate it with all the columns including deleted_at
CREATE VIEW public.articles_admin_list AS
SELECT
  id, 
  created_at, 
  updated_at, 
  title, 
  source_url, 
  source_name,
  summary,
  category, 
  subcategory, 
  score, 
  image_url, 
  published_date,
  is_published, 
  is_draft, 
  admin_notes, 
  scheduled_publish_date,
  era, 
  difficulty, 
  slug,
  deleted_at,  -- Add the deleted_at column
  length(coalesce(raw_content, '')) AS content_length_chars
FROM public.articles
WHERE deleted_at IS NULL;

-- Grant permissions (if needed)
GRANT SELECT ON public.articles_admin_list TO anon, authenticated, service_role;

-- Verify the view now has the deleted_at column
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'articles_admin_list' 
  AND table_schema = 'public'
ORDER BY ordinal_position;

-- Fix any articles stuck with both flags = true
UPDATE public.articles
SET is_draft = false
WHERE is_published = true AND is_draft = true AND deleted_at IS NULL;

-- Verify: should return 0 rows after the fix
SELECT id, title, is_published, is_draft 
FROM public.articles 
WHERE is_published = true AND is_draft = true AND deleted_at IS NULL;

-- Create the bucket via SQL (alternative if UI doesn't work)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'article-images',
  'article-images', 
  true,
  5242880,  -- 5MB max per file
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

-- Allow anyone to read/view images (public bucket)
DROP POLICY IF EXISTS "Public read article-images" ON storage.objects;
CREATE POLICY "Public read article-images"
ON storage.objects FOR SELECT
USING (bucket_id = 'article-images');

-- Allow service role to upload
DROP POLICY IF EXISTS "Service role upload article-images" ON storage.objects;
CREATE POLICY "Service role upload article-images"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'article-images');

-- Allow service role to update
DROP POLICY IF EXISTS "Service role update article-images" ON storage.objects;
CREATE POLICY "Service role update article-images"
ON storage.objects FOR UPDATE
USING (bucket_id = 'article-images');

-- Allow service role to delete
DROP POLICY IF EXISTS "Service role delete article-images" ON storage.objects;
CREATE POLICY "Service role delete article-images"
ON storage.objects FOR DELETE
USING (bucket_id = 'article-images');
